apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - infra/infra.namespace.yml
  - whoami/whoami.namespace.yml
  - bonelli/bonelli.namespace.yml
bases:
  - infra
  - bonelli
  - domain
