# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: wildcard-devyncyphers-io-cert
# spec:
#   dnsNames:
#     - "*.devyncyphers.io"
#   secretName: wildcard-devyncyphers-io-cert
#   issuerRef:
#     name: digitalocean-issuer
